// Generated by CoffeeScript 1.7.1
(function() {
  var browserSync, clean, concat, gulp, locations;

  gulp = require('gulp');

  concat = require('gulp-concat');

  clean = require('gulp-clean');

  browserSync = require('browser-sync');

  locations = {
    css: 'app/**/*.css',
    html: 'app/*.html',
    js: ['app/**/*.js', '!bower_components/**/*.js'],
    lib: ['bower_components/lodash/dist/lodash.min.js', 'bower_components/chartjs/Chart.js', 'bower_components/amcharts/dist/amcharts/amcharts.js', 'bower_components/amcharts/dist/amcharts/serial.js', 'bower_components/amcharts/dist/amcharts/themes/none.js'],
    app: 'app',
    dist: '.dist'
  };

  gulp.task('clean', function() {
    return gulp.src(locations.dist).pipe(clean());
  });

  gulp.task('buildLib', function() {
    return gulp.src(locations.lib).pipe(concat('lib.js')).pipe(gulp.dest(locations.dist));
  });

  gulp.task('buildJs', function() {
    return gulp.src(locations.js).pipe(concat('all.js')).pipe(gulp.dest(locations.dist));
  });

  gulp.task('buildHtmlCss', function() {
    gulp.src(locations.css).pipe(concat('all.css')).pipe(gulp.dest(locations.dist));
    return gulp.src(locations.html).pipe(gulp.dest(locations.dist));
  });

  gulp.task('liveServer', function() {
    browserSync({
      server: {
        baseDir: locations.dist
      }
    });
    gulp.watch(locations.js, ['buildJs']);
    gulp.watch(locations.css, ['buildHtmlCss']);
    gulp.watch(locations.html, ['buildHtmlCss']);
    return gulp.watch(["**"], {
      cwd: locations.dist
    }, browserSync.reload);
  });

  gulp.task('build', ['buildHtmlCss', 'buildLib', 'buildJs']);

  gulp.task('default', ['clean', 'build', 'liveServer']);

}).call(this);
