// Generated by CoffeeScript 1.7.1
(function() {
  var ctx, data, lineGraph, options;

  data = {
    labels: [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
    datasets: [
      {
        label: "Approval",
        fillColor: "rgba(220,220,220,0.2)",
        strokeColor: "rgba(220,220,220,1)",
        pointColor: "rgba(220,220,220,1)",
        pointStrokeColor: "#fff",
        pointHighlightFill: "#fff",
        pointHighlightStroke: "rgba(220,220,220,1)",
        data: [65, 59, 80, 81, 56, 55, 40, 10, 20, 20, 20]
      }
    ]
  };

  options = {
    pointDot: false,
    scaleShowGridLines: false,
    animation: false,
    scaleLabel: ' ',
    scaleBeginAtZero: true,
    scaleLineColor: 'transparent'
  };

  ctx = document.getElementsByTagName('canvas')[0].getContext('2d');

  lineGraph = new Chart(ctx).Line(data, options);

}).call(this);
