// Generated by CoffeeScript 1.7.1
(function() {
  var init, ivl, parse;

  ivl = setInterval(function() {
    if (window.elPresidente) {
      clearInterval(ivl);
      return init(window.elPresidente);
    }
  }, 500);

  init = function(data) {
    var chart, graphConfig, options;
    data = parse(data);
    console.log(data[0]);
    graphConfig = [
      {
        title: "Approval Rating (0-100)",
        fillAlphas: .2,
        valueField: 'approval',
        bullet: 'round',
        bulletSize: 4,
        bulletAlpha: 1,
        lineColor: 'cornflowerblue',
        lineThickness: 1.5
      }
    ];
    options = {
      type: 'serial',
      theme: 'none',
      rotate: true,
      dataProvider: data.slice(0, 2000),
      categoryField: 'time',
      color: '#333',
      creditsPosition: 'bottom-right',
      valueAxes: [
        {
          axisAlpha: 0,
          gridAlpha: 0,
          labelsEnabled: false
        }
      ],
      categoryAxis: {
        autoGridCount: true,
        axisAlpha: 0,
        gridAlpha: 0.03,
        parseDates: true,
        dateFormats: [
          {
            period: 'DD',
            format: 'DD'
          }, {
            period: 'WW',
            format: 'YYYY MMM DD'
          }, {
            period: 'MM',
            format: 'YYYY MMM DD'
          }, {
            period: 'YYYY',
            format: 'YYYY MMM DD'
          }
        ],
        boldPeriodBeginning: false,
        fontSize: 10
      },
      graphs: graphConfig
    };
    return chart = AmCharts.makeChart('AmChart', options);
  };

  parse = function(raw) {
    var d, parsed, _i, _len;
    parsed = _.flatten(raw);
    parsed.reverse();
    for (_i = 0, _len = parsed.length; _i < _len; _i++) {
      d = parsed[_i];
      d.time = new Date(d.start);
    }
    return parsed;
  };

}).call(this);
